/**
 * List of all available module names for tags
 */
const moduleNameTranslation = {
	'20100160': [
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'20500010': [
		'Presentation LUT Module',
		'SOFTCOPY PRESENTATION LUT MODULE ATTRIBUTES'
	],
	'20500020': [
		'DX IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'Presentation LUT Module',
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES',
		'SOFTCOPY PRESENTATION LUT MODULE ATTRIBUTES'
	],
	'52009229': [
		'MULTI-FRAME FUNCTIONAL GROUPS MODULE ATTRIBUTES'
	],
	'52009230': [
		'MULTI-FRAME FUNCTIONAL GROUPS MODULE ATTRIBUTES'
	],
	'54000100': [
		'Waveform Module Attributes'
	],
	'54000110': [
		'Waveform Module Attributes'
	],
	'54000112': [
		'Waveform Module Attributes'
	],
	'54001004': [
		'Waveform Module Attributes'
	],
	'54001006': [
		'Waveform Module Attributes'
	],
	'54001010': [
		'Waveform Module Attributes'
	],
	'56000010': [
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'56000020': [
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00400555': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES'
	],
	'0040a043': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES',
		'Waveform Annotation Module Attributes'
	],
	'0040a136': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES'
	],
	'0040a30a': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES',
		'Slide Coordinates Module Attributes',
		'Waveform Annotation Module Attributes'
	],
	'004008ea': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES',
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES',
		'Slide Coordinates Module Attributes',
		'Waveform Annotation Module Attributes'
	],
	'0040a121': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES'
	],
	'0040a122': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES'
	],
	'0040a123': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES'
	],
	'0040a160': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES'
	],
	'0040a168': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES',
		'Waveform Annotation Module Attributes'
	],
	'00400556': [
		'ACQUISITION CONTEXT MODULE ATTRIBUTES'
	],
	'50xx2000': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'50xx2002': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'50xx2004': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'50xx2006': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'50xx2008': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'50xx200a': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'50xx200c': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'00081140': [
		'AUDIO MODULE ATTRIBUTES',
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'DISPLAYED AREA MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES',
		'LUT Identification Module Attributes',
		'OVERLAY IDENTIFICATION MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'REFERENCED IMAGE MACRO ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00081150': [
		'AUDIO MODULE ATTRIBUTES',
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'CURVE MODULE ATTRIBUTES',
		'DERIVATION IMAGE MACRO ATTRIBUTES',
		'DISPLAYED AREA MODULE ATTRIBUTES',
		'DX SERIES MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GENERAL SERIES MODULE ATTRIBUTES',
		'GENERAL STUDY MODULE ATTRIBUTES',
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES',
		'LUT Identification Module Attributes',
		'NM IMAGE MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'OVERLAY IDENTIFICATION MODULE ATTRIBUTES',
		'PATIENT MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'REFERENCED IMAGE MACRO ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'Waveform Identification Module Attributes',
		'Waveform Module Attributes',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00081155': [
		'AUDIO MODULE ATTRIBUTES',
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'CURVE MODULE ATTRIBUTES',
		'DERIVATION IMAGE MACRO ATTRIBUTES',
		'DISPLAYED AREA MODULE ATTRIBUTES',
		'DX SERIES MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GENERAL SERIES MODULE ATTRIBUTES',
		'GENERAL STUDY MODULE ATTRIBUTES',
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES',
		'LUT Identification Module Attributes',
		'NM IMAGE MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'OVERLAY IDENTIFICATION MODULE ATTRIBUTES',
		'PATIENT MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'REFERENCED IMAGE MACRO ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'Waveform Identification Module Attributes',
		'Waveform Module Attributes',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'50xx200e': [
		'AUDIO MODULE ATTRIBUTES'
	],
	'00181600': [
		'BITMAP DISPLAY SHUTTER MODULE ATTRIBUTES',
		'DISPLAY SHUTTER MODULE'
	],
	'00181623': [
		'BITMAP DISPLAY SHUTTER MODULE ATTRIBUTES'
	],
	'00181622': [
		'BITMAP DISPLAY SHUTTER MODULE ATTRIBUTES',
		'DISPLAY SHUTTER MODULE',
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00189172': [
		'BULK MOTION SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00189173': [
		'BULK MOTION SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00189037': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00189085': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00189070': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00189169': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00181081': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00181082': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00181083': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00181084': [
		'CARDIAC SYNCHRONIZATION MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00189118': [
		'CARDIAC TRIGGER MACRO ATTRIBUTES'
	],
	'00209153': [
		'CARDIAC TRIGGER MACRO ATTRIBUTES'
	],
	'00181244': [
		'CINE MODULE ATTRIBUTES'
	],
	'00181063': [
		'CINE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00181065': [
		'CINE MODULE ATTRIBUTES',
		'SC MULTI-FRAME VECTOR MODULE ATTRIBUTES',
		'SCMULTI-FRAME VECTOR MODULE ATTRIBUTES'
	],
	'00082142': [
		'CINE MODULE ATTRIBUTES'
	],
	'00082143': [
		'CINE MODULE ATTRIBUTES'
	],
	'00082144': [
		'CINE MODULE ATTRIBUTES'
	],
	'00180040': [
		'CINE MODULE ATTRIBUTES'
	],
	'00181066': [
		'CINE MODULE ATTRIBUTES'
	],
	'00181067': [
		'CINE MODULE ATTRIBUTES'
	],
	'00180072': [
		'CINE MODULE ATTRIBUTES'
	],
	'00181242': [
		'CINE MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'NM PHASE MODULE ATTRIBUTES',
		'NM TOMO ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00120060': [
		'CLINICAL TRIAL SERIES MODULE ATTRIBUTES'
	],
	'00120050': [
		'CLINICAL TRIAL STUDY MODULE ATTRIBUTES'
	],
	'00120051': [
		'CLINICAL TRIAL STUDY MODULE ATTRIBUTES'
	],
	'00120010': [
		'CLINICAL TRIAL SUBJECT MODULE ATTRIBUTES'
	],
	'00120020': [
		'CLINICAL TRIAL SUBJECT MODULE ATTRIBUTES'
	],
	'00120021': [
		'CLINICAL TRIAL SUBJECT MODULE ATTRIBUTES'
	],
	'00120030': [
		'CLINICAL TRIAL SUBJECT MODULE ATTRIBUTES'
	],
	'00120031': [
		'CLINICAL TRIAL SUBJECT MODULE ATTRIBUTES'
	],
	'00120040': [
		'CLINICAL TRIAL SUBJECT MODULE ATTRIBUTES'
	],
	'00120042': [
		'CLINICAL TRIAL SUBJECT MODULE ATTRIBUTES'
	],
	'00180010': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00180012': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181040': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00180014': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'0018002a': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181041': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181042': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181043': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181044': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181046': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181047': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181048': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00181049': [
		'CONTRAST/BOLUS MODULE ATTRIBUTES'
	],
	'00280004': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM IMAGE PIXEL MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00180060': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00181004': [
		'CR IMAGE MODULE ATTRIBUTES'
	],
	'00181110': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'DX POSITIONING MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES',
		'NM TOMO ACQUISITION MODULE ATTRIBUTES',
		'XA POSITIONER MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'XRF POSITIONER MODULE ATTRIBUTES'
	],
	'00181111': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'DX POSITIONING MODULE ATTRIBUTES',
		'XA POSITIONER MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'XRF POSITIONER MODULE ATTRIBUTES'
	],
	'00181150': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00181151': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00181152': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00181153': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00181164': [
		'CR IMAGE MODULE ATTRIBUTES',
		'DX DETECTOR MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181170': [
		'CR IMAGE MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES'
	],
	'00181400': [
		'CR IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00181401': [
		'CR IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES'
	],
	'00181402': [
		'CR IMAGE MODULE ATTRIBUTES'
	],
	'00181403': [
		'CR IMAGE MODULE ATTRIBUTES'
	],
	'00181404': [
		'CR IMAGE MODULE ATTRIBUTES'
	],
	'00181405': [
		'CR IMAGE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00186000': [
		'CR IMAGE MODULE ATTRIBUTES',
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00180015': [
		'CR SERIES MODULE ATTRIBUTES',
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00185101': [
		'CR SERIES MODULE ATTRIBUTES',
		'DX POSITIONING MODULE ATTRIBUTES'
	],
	'00181160': [
		'CR SERIES MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'X-RAY FILTRATION MODULE ATTRIBUTES'
	],
	'00181180': [
		'CR SERIES MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00181190': [
		'CR SERIES MODULE ATTRIBUTES',
		'CT IMAGE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00181260': [
		'CR SERIES MODULE ATTRIBUTES'
	],
	'00181261': [
		'CR SERIES MODULE ATTRIBUTES'
	],
	'00080008': [
		'CT IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE DESCRIPTION MACRO ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00280002': [
		'CT IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM IMAGE PIXEL MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00280100': [
		'CT IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM IMAGE PIXEL MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00280101': [
		'CT IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'NM IMAGE PIXEL MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00280102': [
		'CT IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'NM IMAGE PIXEL MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00281053': [
		'CT IMAGE MODULE ATTRIBUTES',
		'DX IMAGE MODULE ATTRIBUTES',
		'MODALITY LUT MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'PIXEL VALUE TRANSFORMATION MACRO ATTRIBUTES',
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00200012': [
		'CT IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00180022': [
		'CT IMAGE MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00180090': [
		'CT IMAGE MODULE ATTRIBUTES'
	],
	'00181100': [
		'CT IMAGE MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00181120': [
		'CT IMAGE MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00181130': [
		'CT IMAGE MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00181140': [
		'CT IMAGE MODULE ATTRIBUTES',
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00181210': [
		'CT IMAGE MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00080025': [
		'CURVE IDENTIFICATION MODULE ATTRIBUTES'
	],
	'00080035': [
		'CURVE IDENTIFICATION MODULE ATTRIBUTES'
	],
	'00081130': [
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00081145': [
		'CURVE IDENTIFICATION MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'50xx0005': [
		'CURVE MODULE ATTRIBUTES',
		'PET CURVE MODULE ATTRIBUTES'
	],
	'50xx0010': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0020': [
		'CURVE MODULE ATTRIBUTES',
		'PET CURVE MODULE ATTRIBUTES'
	],
	'50xx0103': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx3000': [
		'CURVE MODULE ATTRIBUTES',
		'PET CURVE MODULE ATTRIBUTES'
	],
	'50xx0022': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0030': [
		'CURVE MODULE ATTRIBUTES',
		'PET CURVE MODULE ATTRIBUTES'
	],
	'50xx0040': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0104': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0105': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0106': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0110': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0112': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx0114': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx2500': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx2600': [
		'CURVE MODULE ATTRIBUTES'
	],
	'50xx2610': [
		'CURVE MODULE ATTRIBUTES'
	],
	'00089124': [
		'DERIVATION IMAGE MACRO ATTRIBUTES'
	],
	'00082111': [
		'DERIVATION IMAGE MACRO ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00089215': [
		'DERIVATION IMAGE MACRO ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES'
	],
	'00082112': [
		'DERIVATION IMAGE MACRO ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES'
	],
	'00081160': [
		'DERIVATION IMAGE MACRO ATTRIBUTES',
		'DISPLAYED AREA MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'REFERENCED IMAGE MACRO ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES'
	],
	'0040a170': [
		'DERIVATION IMAGE MACRO ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'REFERENCED IMAGE MACRO ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00500010': [
		'DEVICE MODULE ATTRIBUTES'
	],
	'00500014': [
		'DEVICE MODULE ATTRIBUTES'
	],
	'00500016': [
		'DEVICE MODULE ATTRIBUTES'
	],
	'00500017': [
		'DEVICE MODULE ATTRIBUTES'
	],
	'00500018': [
		'DEVICE MODULE ATTRIBUTES'
	],
	'00500019': [
		'DEVICE MODULE ATTRIBUTES'
	],
	'00500020': [
		'DEVICE MODULE ATTRIBUTES'
	],
	'4ffe0001': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000005': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES',
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000010': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000015': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000020': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'fffafffa': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000100': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000105': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000110': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000115': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000120': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000305': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'04000310': [
		'DIGITAL SIGNATURES MACRO ATTRIBUTES'
	],
	'00181602': [
		'DISPLAY SHUTTER MODULE'
	],
	'00181604': [
		'DISPLAY SHUTTER MODULE'
	],
	'00181606': [
		'DISPLAY SHUTTER MODULE'
	],
	'00181608': [
		'DISPLAY SHUTTER MODULE'
	],
	'00181610': [
		'DISPLAY SHUTTER MODULE'
	],
	'00181612': [
		'DISPLAY SHUTTER MODULE'
	],
	'00181620': [
		'DISPLAY SHUTTER MODULE'
	],
	'0070005a': [
		'DISPLAYED AREA MODULE ATTRIBUTES'
	],
	'00700052': [
		'DISPLAYED AREA MODULE ATTRIBUTES'
	],
	'00700053': [
		'DISPLAYED AREA MODULE ATTRIBUTES'
	],
	'00700100': [
		'DISPLAYED AREA MODULE ATTRIBUTES'
	],
	'00700101': [
		'DISPLAYED AREA MODULE ATTRIBUTES'
	],
	'00700102': [
		'DISPLAYED AREA MODULE ATTRIBUTES'
	],
	'00700103': [
		'DISPLAYED AREA MODULE ATTRIBUTES'
	],
	'00200062': [
		'DX ANATOMY IMAGED MODULE ATTRIBUTES'
	],
	'00082218': [
		'DX ANATOMY IMAGED MODULE ATTRIBUTES',
		'FRAME ANATOMY MACRO ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00082220': [
		'DX ANATOMY IMAGED MODULE ATTRIBUTES',
		'FRAME ANATOMY MACRO ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00082228': [
		'DX ANATOMY IMAGED MODULE ATTRIBUTES',
		'FRAME ANATOMY MACRO ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00082230': [
		'DX ANATOMY IMAGED MODULE ATTRIBUTES',
		'FRAME ANATOMY MACRO ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00187004': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187005': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187006': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187008': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'0018700a': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'0018700c': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'0018700e': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187011': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187012': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187014': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187016': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'0018701a': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187000': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187001': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00181147': [
		'DX DETECTOR MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181149': [
		'DX DETECTOR MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00187030': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187032': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187034': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187020': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187022': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187024': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187026': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00187028': [
		'DX DETECTOR MODULE ATTRIBUTES'
	],
	'00281051': [
		'DX IMAGE MODULE ATTRIBUTES',
		'FRAME VOI LUT MACRO ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'VOI LUT MODULE ATTRIBUTES'
	],
	'00281055': [
		'DX IMAGE MODULE ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'VOI LUT MODULE ATTRIBUTES'
	],
	'00280103': [
		'DX IMAGE MODULE ATTRIBUTES',
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES'
	],
	'00281040': [
		'DX IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00281041': [
		'DX IMAGE MODULE ATTRIBUTES'
	],
	'00281052': [
		'DX IMAGE MODULE ATTRIBUTES',
		'MODALITY LUT MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'PIXEL VALUE TRANSFORMATION MACRO ATTRIBUTES',
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00281054': [
		'DX IMAGE MODULE ATTRIBUTES',
		'MODALITY LUT MODULE ATTRIBUTES',
		'PIXEL VALUE TRANSFORMATION MACRO ATTRIBUTES',
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00282110': [
		'DX IMAGE MODULE ATTRIBUTES',
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'NM IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00282112': [
		'DX IMAGE MODULE ATTRIBUTES',
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES'
	],
	'00200020': [
		'DX IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES'
	],
	'00500004': [
		'DX IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00280301': [
		'DX IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00283010': [
		'DX IMAGE MODULE ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'VOI LUT MODULE ATTRIBUTES'
	],
	'00283002': [
		'DX IMAGE MODULE ATTRIBUTES',
		'MODALITY LUT MODULE ATTRIBUTES',
		'Presentation LUT Module',
		'SOFTCOPY PRESENTATION LUT MODULE ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'VOI LUT MODULE ATTRIBUTES'
	],
	'00283003': [
		'DX IMAGE MODULE ATTRIBUTES',
		'MODALITY LUT MODULE ATTRIBUTES',
		'Presentation LUT Module',
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES',
		'SOFTCOPY PRESENTATION LUT MODULE ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'VOI LUT MODULE ATTRIBUTES'
	],
	'00283006': [
		'DX IMAGE MODULE ATTRIBUTES',
		'MODALITY LUT MODULE ATTRIBUTES',
		'Presentation LUT Module',
		'SOFTCOPY PRESENTATION LUT MODULE ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'VOI LUT MODULE ATTRIBUTES'
	],
	'00281050': [
		'DX IMAGE MODULE ATTRIBUTES',
		'FRAME VOI LUT MACRO ATTRIBUTES',
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES',
		'VOI LUT MODULE ATTRIBUTES'
	],
	'00185104': [
		'DX POSITIONING MODULE ATTRIBUTES'
	],
	'00185100': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00540220': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00540222': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00540410': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'NM/PET PATIENT ORIENTATION MODULE ATTRIBUTES'
	],
	'00540412': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'NM/PET PATIENT ORIENTATION MODULE ATTRIBUTES'
	],
	'00540414': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'NM/PET PATIENT ORIENTATION MODULE ATTRIBUTES'
	],
	'00181508': [
		'DX POSITIONING MODULE ATTRIBUTES'
	],
	'00181510': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'XA POSITIONER MODULE ATTRIBUTES'
	],
	'00181511': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'XA POSITIONER MODULE ATTRIBUTES'
	],
	'00181530': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'XA POSITIONER MODULE ATTRIBUTES'
	],
	'00181531': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'XA POSITIONER MODULE ATTRIBUTES'
	],
	'00181450': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'XRF POSITIONER MODULE ATTRIBUTES'
	],
	'0018113a': [
		'DX POSITIONING MODULE ATTRIBUTES'
	],
	'00181138': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'X-RAY TABLE MODULE ATTRIBUTES'
	],
	'001811a0': [
		'DX POSITIONING MODULE ATTRIBUTES',
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'001811a2': [
		'DX POSITIONING MODULE ATTRIBUTES'
	],
	'00080060': [
		'DX SERIES MODULE ATTRIBUTES',
		'GENERAL SERIES MODULE ATTRIBUTES',
		'HARDCOPY EQUIPMENT MODULE ATTRIBUTES',
		'PRESENTATION SERIES MODULE ATTRIBUTES',
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00081111': [
		'DX SERIES MODULE ATTRIBUTES',
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00080068': [
		'DX SERIES MODULE ATTRIBUTES'
	],
	'04000550': [
		'ENCRYPTED ATTRIBUTES DATA SET ATTRIBUTES'
	],
	'00289099': [
		'ENHANCED MR IMAGE MODULE ATTRIBUTES'
	],
	'00180088': [
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00880200': [
		'ENHANCED MR IMAGE MODULE ATTRIBUTES',
		'GENERAL IMAGE MODULE ATTRIBUTES'
	],
	'00209071': [
		'FRAME ANATOMY MACRO ATTRIBUTES'
	],
	'00209072': [
		'FRAME ANATOMY MACRO ATTRIBUTES'
	],
	'00209111': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00209156': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00189151': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00189074': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00189220': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00189236': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00189214': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00209157': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00209128': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00209056': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00209057': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00209158': [
		'FRAME CONTENT MACRO ATTRIBUTES'
	],
	'00200052': [
		'FRAME OF REFERENCE MODULE ATTRIBUTES'
	],
	'00201040': [
		'FRAME OF REFERENCE MODULE ATTRIBUTES'
	],
	'00286010': [
		'FRAME POINTERS MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00286020': [
		'FRAME POINTERS MODULE ATTRIBUTES'
	],
	'00286022': [
		'FRAME POINTERS MODULE ATTRIBUTES'
	],
	'00289132': [
		'FRAME VOI LUT MACRO ATTRIBUTES'
	],
	'00080070': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080080': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080081': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00081010': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00081040': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00081090': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00181000': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00181020': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00181050': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00181200': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00181201': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00280120': [
		'GENERAL EQUIPMENT MODULE ATTRIBUTES'
	],
	'00200013': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO',
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES',
		'Waveform Identification Module Attributes'
	],
	'00080023': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO',
		'Waveform Identification Module Attributes'
	],
	'00080033': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO',
		'VL IMAGE MODULE ATTRIBUTES',
		'Waveform Identification Module Attributes'
	],
	'00080022': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00080032': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'0008002a': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO',
		'US IMAGE MODULE ATTRIBUTES',
		'Waveform Identification Module Attributes'
	],
	'0008113a': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00201002': [
		'GENERAL IMAGE MODULE ATTRIBUTES'
	],
	'00204000': [
		'GENERAL IMAGE MODULE ATTRIBUTES',
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00280300': [
		'GENERAL IMAGE MODULE ATTRIBUTES'
	],
	'0020000e': [
		'GENERAL SERIES MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES'
	],
	'00200011': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00200060': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00080021': [
		'GENERAL SERIES MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00080031': [
		'GENERAL SERIES MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00081050': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00081052': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00181030': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'0008103e': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00081072': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00280108': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00280109': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400275': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00401001': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400009': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400007': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400008': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400253': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400244': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400245': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400254': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00400260': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'00081070': [
		'GENERAL SERIES MODULE ATTRIBUTES'
	],
	'0020000d': [
		'GENERAL STUDY MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES'
	],
	'00080020': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00080030': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00080090': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00080096': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00200010': [
		'GENERAL STUDY MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES'
	],
	'00080050': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00081030': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00081048': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00081049': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00081060': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00081062': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00081110': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00081032': [
		'GENERAL STUDY MODULE ATTRIBUTES'
	],
	'00700001': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700002': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES',
		'GRAPHIC LAYER MODULE ATTRIBUTES'
	],
	'00700008': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700003': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700004': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700006': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES',
		'Waveform Annotation Module Attributes'
	],
	'00700010': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700011': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700012': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700014': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700015': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700009': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700005': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700020': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700021': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700022': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700023': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700024': [
		'GRAPHIC ANNOTATION MODULE ATTRIBUTES'
	],
	'00700060': [
		'GRAPHIC LAYER MODULE ATTRIBUTES'
	],
	'00700062': [
		'GRAPHIC LAYER MODULE ATTRIBUTES'
	],
	'00700066': [
		'GRAPHIC LAYER MODULE ATTRIBUTES'
	],
	'00700067': [
		'GRAPHIC LAYER MODULE ATTRIBUTES'
	],
	'00700068': [
		'GRAPHIC LAYER MODULE ATTRIBUTES'
	],
	'00181166': [
		'GRID MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00187040': [
		'GRID MODULE ATTRIBUTES'
	],
	'00187041': [
		'GRID MODULE ATTRIBUTES'
	],
	'00187042': [
		'GRID MODULE ATTRIBUTES'
	],
	'00187044': [
		'GRID MODULE ATTRIBUTES'
	],
	'00187046': [
		'GRID MODULE ATTRIBUTES'
	],
	'00187048': [
		'GRID MODULE ATTRIBUTES'
	],
	'0018704c': [
		'GRID MODULE ATTRIBUTES'
	],
	'00280006': [
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'VL IMAGE MODULE ATTRIBUTES'
	],
	'00280010': [
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00280011': [
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00280034': [
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES'
	],
	'7fe00010': [
		'HARDCOPY COLOR IMAGE MODULE ATTRIBUTES',
		'HARDCOPY GRAYSCALE IMAGE MODULE ATTRIBUTES',
		'IMAGE PIXEL MODULE ATTRIBUTES'
	],
	'00181011': [
		'HARDCOPY EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181017': [
		'HARDCOPY EQUIPMENT MODULE ATTRIBUTES'
	],
	'0018101a': [
		'HARDCOPY EQUIPMENT MODULE ATTRIBUTES'
	],
	'0018101b': [
		'HARDCOPY EQUIPMENT MODULE ATTRIBUTES'
	],
	'00603000': [
		'IMAGE HISTOGRAM MODULE ATTRIBUTES'
	],
	'00603002': [
		'IMAGE HISTOGRAM MODULE ATTRIBUTES'
	],
	'00603004': [
		'IMAGE HISTOGRAM MODULE ATTRIBUTES'
	],
	'00603006': [
		'IMAGE HISTOGRAM MODULE ATTRIBUTES'
	],
	'00603008': [
		'IMAGE HISTOGRAM MODULE ATTRIBUTES'
	],
	'00603010': [
		'IMAGE HISTOGRAM MODULE ATTRIBUTES'
	],
	'00603020': [
		'IMAGE HISTOGRAM MODULE ATTRIBUTES'
	],
	'00280106': [
		'IMAGE PIXEL MODULE ATTRIBUTES'
	],
	'00280107': [
		'IMAGE PIXEL MODULE ATTRIBUTES'
	],
	'00281101': [
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'PALETTE COLOR LOOKUP MODULE',
		'SUPPLEMENTAL PALETTE COLOR TABLE LOOKUP MODULE ATTRIBUTES'
	],
	'00281102': [
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'PALETTE COLOR LOOKUP MODULE',
		'SUPPLEMENTAL PALETTE COLOR TABLE LOOKUP MODULE ATTRIBUTES'
	],
	'00281103': [
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'PALETTE COLOR LOOKUP MODULE',
		'SUPPLEMENTAL PALETTE COLOR TABLE LOOKUP MODULE ATTRIBUTES'
	],
	'00281201': [
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'PALETTE COLOR LOOKUP MODULE',
		'SUPPLEMENTAL PALETTE COLOR TABLE LOOKUP MODULE ATTRIBUTES'
	],
	'00281202': [
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'PALETTE COLOR LOOKUP MODULE',
		'SUPPLEMENTAL PALETTE COLOR TABLE LOOKUP MODULE ATTRIBUTES'
	],
	'00281203': [
		'IMAGE PIXEL MODULE ATTRIBUTES',
		'PALETTE COLOR LOOKUP MODULE',
		'SUPPLEMENTAL PALETTE COLOR TABLE LOOKUP MODULE ATTRIBUTES'
	],
	'00280030': [
		'IMAGE PLANE MODULE ATTRIBUTES',
		'NM IMAGE PIXEL MODULE ATTRIBUTES',
		'PIXEL MEASURES MACRO ATTRIBUTES'
	],
	'00200037': [
		'IMAGE PLANE MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES',
		'PLANE ORIENTATION MACRO ATTRIBUTES'
	],
	'00200032': [
		'IMAGE PLANE MODULE ATTRIBUTES',
		'NM DETECTOR MODULE ATTRIBUTES',
		'PLANE POSITION MACRO ATTRIBUTES'
	],
	'00180050': [
		'IMAGE PLANE MODULE ATTRIBUTES',
		'PIXEL MEASURES MACRO ATTRIBUTES'
	],
	'00201041': [
		'IMAGE PLANE MODULE ATTRIBUTES'
	],
	'00200026': [
		'LUT Identification Module Attributes'
	],
	'00286100': [
		'MASK MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00286101': [
		'MASK MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00286102': [
		'MASK MODULE ATTRIBUTES'
	],
	'00286110': [
		'MASK MODULE ATTRIBUTES'
	],
	'00286112': [
		'MASK MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00286114': [
		'MASK MODULE ATTRIBUTES'
	],
	'00286120': [
		'MASK MODULE ATTRIBUTES'
	],
	'00286190': [
		'MASK MODULE ATTRIBUTES'
	],
	'00281090': [
		'MASK MODULE ATTRIBUTES',
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00283000': [
		'MODALITY LUT MODULE ATTRIBUTES'
	],
	'00283004': [
		'MODALITY LUT MODULE ATTRIBUTES'
	],
	'00189119': [
		'MR AVERAGES MACRO ATTRIBUTES'
	],
	'00180083': [
		'MR AVERAGES MACRO ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00189117': [
		'MR DIFFUSION MACRO ATTRIBUTES'
	],
	'00189087': [
		'MR DIFFUSION MACRO ATTRIBUTES'
	],
	'00189075': [
		'MR DIFFUSION MACRO ATTRIBUTES'
	],
	'00189076': [
		'MR DIFFUSION MACRO ATTRIBUTES'
	],
	'00189089': [
		'MR DIFFUSION MACRO ATTRIBUTES'
	],
	'00189147': [
		'MR DIFFUSION MACRO ATTRIBUTES'
	],
	'00189114': [
		'MR ECHO MACRO ATTRIBUTES'
	],
	'00189082': [
		'MR ECHO MACRO ATTRIBUTES'
	],
	'00189125': [
		'MR FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00181312': [
		'MR FOV/GEOMETRY MACRO ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00189058': [
		'MR FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189231': [
		'MR FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189232': [
		'MR FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00180093': [
		'MR FOV/GEOMETRY MACRO ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00180094': [
		'MR FOV/GEOMETRY MACRO ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189073': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00280008': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO',
		'MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00209228': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00209161': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00209162': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00209163': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00089121': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00089092': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00089154': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00089237': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00189004': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00189100': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00180087': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO',
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00189174': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00189175': [
		'MR IMAGE AND SPECTROSCOPY INSTANCE MACRO'
	],
	'00089007': [
		'MR IMAGE DESCRIPTION MACRO ATTRIBUTES'
	],
	'00089205': [
		'MR IMAGE DESCRIPTION MACRO ATTRIBUTES'
	],
	'00089206': [
		'MR IMAGE DESCRIPTION MACRO ATTRIBUTES'
	],
	'00089207': [
		'MR IMAGE DESCRIPTION MACRO ATTRIBUTES'
	],
	'00089208': [
		'MR IMAGE DESCRIPTION MACRO ATTRIBUTES'
	],
	'00089209': [
		'MR IMAGE DESCRIPTION MACRO ATTRIBUTES'
	],
	'00189226': [
		'MR IMAGE FRAME TYPE MACRO ATTRIBUTES'
	],
	'00180020': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180021': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180023': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00180080': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00180081': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180091': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00180082': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00181060': [
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00180024': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180025': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180084': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180085': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180086': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180089': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00180095': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00181062': [
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00181080': [
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00181085': [
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET MULTI-GATED ACQUISITION MODULE ATTRIBUTES'
	],
	'00181086': [
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET MULTI-GATED ACQUISITION MODULE ATTRIBUTES'
	],
	'00181088': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR IMAGE MODULE ATTRIBUTES',
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00181090': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00181094': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00181250': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00181251': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR TRANSMIT COIL MACRO ATTRIBUTES'
	],
	'00181310': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00181314': [
		'MR IMAGE MODULE ATTRIBUTES',
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00181316': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00181315': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00181318': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00200100': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00200105': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00200110': [
		'MR IMAGE MODULE ATTRIBUTES'
	],
	'00189006': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189020': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189022': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189028': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189030': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189218': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189019': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189219': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189035': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189184': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES'
	],
	'00189098': [
		'MR IMAGING MODIFIER MACRO ATTRIBUTES',
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189152': [
		'MR METABOLITE MAP MACRO ATTRIBUTES'
	],
	'00189080': [
		'MR METABOLITE MAP MACRO ATTRIBUTES'
	],
	'00189084': [
		'MR METABOLITE MAP MACRO ATTRIBUTES'
	],
	'00189195': [
		'MR METABOLITE MAP MACRO ATTRIBUTES'
	],
	'00189196': [
		'MR METABOLITE MAP MACRO ATTRIBUTES'
	],
	'00189115': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189009': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189079': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189010': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189183': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189016': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189021': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189026': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189027': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189081': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189036': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189077': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189078': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189069': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189155': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189168': [
		'MR MODIFIER MACRO ATTRIBUTES'
	],
	'00189005': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189008': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189011': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189012': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189014': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189015': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189017': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189018': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189024': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189025': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189029': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189032': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189034': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189033': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189094': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189093': [
		'MR PULSE SEQUENCE MODULE ATTRIBUTES',
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189042': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189041': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189043': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189044': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189045': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189047': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189048': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189046': [
		'MR RECEIVE COIL MACRO ATTRIBUTES'
	],
	'00189107': [
		'MR SPATIAL SATURATION MACRO ATTRIBUTES'
	],
	'00189104': [
		'MR SPATIAL SATURATION MACRO ATTRIBUTES',
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189105': [
		'MR SPATIAL SATURATION MACRO ATTRIBUTES',
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189106': [
		'MR SPATIAL SATURATION MACRO ATTRIBUTES',
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00289001': [
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00289002': [
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00289108': [
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00289003': [
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00289235': [
		'MR SPECTROSCOPY DATA MODULE ATTRIBUTES'
	],
	'00189103': [
		'MR SPECTROSCOPY FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189127': [
		'MR SPECTROSCOPY FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189095': [
		'MR SPECTROSCOPY FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189234': [
		'MR SPECTROSCOPY FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189159': [
		'MR SPECTROSCOPY FOV/GEOMETRY MACRO ATTRIBUTES'
	],
	'00189227': [
		'MR SPECTROSCOPY FRAME TYPE MACRO ATTRIBUTES'
	],
	'00189052': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189053': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189054': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189126': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189060': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189061': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189062': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189063': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189064': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189065': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189066': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189067': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189101': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189198': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189199': [
		'MR SPECTROSCOPY MODULE ATTRIBUTES'
	],
	'00189200': [
		'MR SPECTROSCOPY PULSE SEQUENCE MODULE ATTRIBUTES'
	],
	'00189112': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189239': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189179': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189181': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189180': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189182': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189176': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189178': [
		'MR TIMING AND RELATED PARAMETERS MACRO ATTRIBUTES'
	],
	'00189049': [
		'MR TRANSMIT COIL MACRO ATTRIBUTES'
	],
	'00189050': [
		'MR TRANSMIT COIL MACRO ATTRIBUTES'
	],
	'00189051': [
		'MR TRANSMIT COIL MACRO ATTRIBUTES'
	],
	'00189197': [
		'MR VELOCITY ENCODING MACRO ATTRIBUTES'
	],
	'00189090': [
		'MR VELOCITY ENCODING MACRO ATTRIBUTES'
	],
	'00189091': [
		'MR VELOCITY ENCODING MACRO ATTRIBUTES'
	],
	'00189217': [
		'MR VELOCITY ENCODING MACRO ATTRIBUTES'
	],
	'00209221': [
		'MULTI-FRAME DIMENSION MODULE ATTRIBUTES'
	],
	'00209164': [
		'MULTI-FRAME DIMENSION MODULE ATTRIBUTES',
		'MULTI-FRAME DIMENSION MODULE ATTRIBUTES'
	],
	'00209165': [
		'MULTI-FRAME DIMENSION MODULE ATTRIBUTES'
	],
	'00209213': [
		'MULTI-FRAME DIMENSION MODULE ATTRIBUTES'
	],
	'00209167': [
		'MULTI-FRAME DIMENSION MODULE ATTRIBUTES'
	],
	'00209238': [
		'MULTI-FRAME DIMENSION MODULE ATTRIBUTES'
	],
	'00280009': [
		'MULTI-FRAME MODULE ATTRIBUTES',
		'NM MULTI-FRAME MODULE ATTRIBUTES',
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES',
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'60xx0015': [
		'MULTI-FRAME OVERLAY MODULE ATTRIBUTES'
	],
	'60xx0051': [
		'MULTI-FRAME OVERLAY MODULE ATTRIBUTES'
	],
	'00540022': [
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00181181': [
		'NM DETECTOR MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00181182': [
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00181183': [
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00181184': [
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00280032': [
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00280031': [
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00181145': [
		'NM DETECTOR MODULE ATTRIBUTES'
	],
	'00540200': [
		'NM DETECTOR MODULE ATTRIBUTES',
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00181142': [
		'NM DETECTOR MODULE ATTRIBUTES',
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00540400': [
		'NM IMAGE MODULE ATTRIBUTES'
	],
	'00180070': [
		'NM IMAGE MODULE ATTRIBUTES'
	],
	'00180071': [
		'NM IMAGE MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00181131': [
		'NM IMAGE MODULE ATTRIBUTES',
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00181243': [
		'NM IMAGE MODULE ATTRIBUTES'
	],
	'00185020': [
		'NM IMAGE MODULE ATTRIBUTES',
		'PET CURVE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00280051': [
		'NM IMAGE MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00181301': [
		'NM IMAGE MODULE ATTRIBUTES'
	],
	'00181300': [
		'NM IMAGE MODULE ATTRIBUTES'
	],
	'00181302': [
		'NM IMAGE MODULE ATTRIBUTES'
	],
	'00181061': [
		'NM IMAGE MODULE ATTRIBUTES',
		'PET MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'Synchronization Module Attributes'
	],
	'00540012': [
		'NM ISOTOPE MODULE ATTRIBUTES'
	],
	'00540018': [
		'NM ISOTOPE MODULE ATTRIBUTES'
	],
	'00540013': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00540015': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00540300': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00181070': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00540302': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES',
		'THERAPY MODULE ATTRIBUTES'
	],
	'00181071': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00181072': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00181073': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00181074': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00540306': [
		'NM ISOTOPE MODULE ATTRIBUTES'
	],
	'00540308': [
		'NM ISOTOPE MODULE ATTRIBUTES'
	],
	'00181045': [
		'NM ISOTOPE MODULE ATTRIBUTES'
	],
	'00540017': [
		'NM ISOTOPE MODULE ATTRIBUTES'
	],
	'00180031': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00540304': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00180026': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00180034': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00180029': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES',
		'THERAPY MODULE ATTRIBUTES'
	],
	'00180035': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES',
		'THERAPY MODULE ATTRIBUTES'
	],
	'00180027': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES',
		'THERAPY MODULE ATTRIBUTES'
	],
	'00180028': [
		'NM ISOTOPE MODULE ATTRIBUTES',
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00540010': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540011': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540020': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540021': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540030': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540031': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540050': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540051': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540060': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540061': [
		'NM MULTI-FRAME MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00540070': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540071': [
		'NM MULTI-FRAME MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00540080': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540081': [
		'NM MULTI-FRAME MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00540090': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540100': [
		'NM MULTI-FRAME MODULE ATTRIBUTES'
	],
	'00540062': [
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES'
	],
	'00181064': [
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES',
		'PET MULTI-GATED ACQUISITION MODULE ATTRIBUTES'
	],
	'00540063': [
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES'
	],
	'00540072': [
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES'
	],
	'00540073': [
		'NM MULTI-GATED ACQUISITION MODULE ATTRIBUTES'
	],
	'00540032': [
		'NM PHASE MODULE ATTRIBUTES'
	],
	'00540036': [
		'NM PHASE MODULE ATTRIBUTES'
	],
	'00540038': [
		'NM PHASE MODULE ATTRIBUTES'
	],
	'00540033': [
		'NM PHASE MODULE ATTRIBUTES'
	],
	'00540210': [
		'NM PHASE MODULE ATTRIBUTES'
	],
	'00540211': [
		'NM PHASE MODULE ATTRIBUTES'
	],
	'00540052': [
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00181144': [
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00181143': [
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00540053': [
		'NM TOMO ACQUISITION MODULE ATTRIBUTES'
	],
	'00540202': [
		'NM TOMO ACQUISITION MODULE ATTRIBUTES',
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00080102': [
		'NM/PET PATIENT ORIENTATION MODULE ATTRIBUTES',
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00200022': [
		'OVERLAY IDENTIFICATION MODULE ATTRIBUTES'
	],
	'00080024': [
		'OVERLAY IDENTIFICATION MODULE ATTRIBUTES'
	],
	'00080034': [
		'OVERLAY IDENTIFICATION MODULE ATTRIBUTES'
	],
	'60xx0010': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx0011': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx0040': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx0050': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx0100': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx0102': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx0022': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx0045': [
		'OVERLAY PLANE MODULE ATTRIBUTES',
		'US IMAGE MODULE ATTRIBUTES'
	],
	'60xx1500': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx1301': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx1302': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx1303': [
		'OVERLAY PLANE MODULE ATTRIBUTES'
	],
	'60xx1001': [
		'OVERLAY/CURVE ACTIVATION MODULE ATTRIBUTES'
	],
	'50xx1001': [
		'OVERLAY/CURVE ACTIVATION MODULE ATTRIBUTES'
	],
	'00281199': [
		'PALETTE COLOR LOOKUP MODULE'
	],
	'00281221': [
		'PALETTE COLOR LOOKUP MODULE'
	],
	'00281222': [
		'PALETTE COLOR LOOKUP MODULE'
	],
	'00281223': [
		'PALETTE COLOR LOOKUP MODULE'
	],
	'00100010': [
		'PATIENT MODULE ATTRIBUTES',
		'PATIENT SUMMARY MODULE ATTRIBUTES'
	],
	'00100020': [
		'PATIENT MODULE ATTRIBUTES',
		'PATIENT SUMMARY MODULE ATTRIBUTES'
	],
	'00100030': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00100040': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00081120': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00100032': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00101000': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00101001': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00102160': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00104000': [
		'PATIENT MODULE ATTRIBUTES'
	],
	'00081080': [
		'PATIENT STUDY MODULE ATTRIBUTES'
	],
	'00081084': [
		'PATIENT STUDY MODULE ATTRIBUTES'
	],
	'00101010': [
		'PATIENT STUDY MODULE ATTRIBUTES'
	],
	'00101020': [
		'PATIENT STUDY MODULE ATTRIBUTES'
	],
	'00101030': [
		'PATIENT STUDY MODULE ATTRIBUTES'
	],
	'00102180': [
		'PATIENT STUDY MODULE ATTRIBUTES'
	],
	'001021b0': [
		'PATIENT STUDY MODULE ATTRIBUTES'
	],
	'00541401': [
		'PET CURVE MODULE ATTRIBUTES'
	],
	'00541400': [
		'PET CURVE MODULE ATTRIBUTES'
	],
	'00541300': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00541330': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00541311': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00541320': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00541321': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00541322': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00541323': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00541324': [
		'PET IMAGE MODULE ATTRIBUTES'
	],
	'00540016': [
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00181075': [
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00181076': [
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00181077': [
		'PET ISOTOPE MODULE ATTRIBUTES'
	],
	'00541001': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541002': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541000': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541004': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00540101': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541100': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541101': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541105': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541102': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541103': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541104': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00180073': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00180074': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00180075': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00181121': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541200': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541201': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541202': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541203': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541210': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00540014': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00541220': [
		'PET SERIES MODULE ATTRIBUTES'
	],
	'00289110': [
		'PIXEL MEASURES MACRO ATTRIBUTES'
	],
	'00289145': [
		'PIXEL VALUE TRANSFORMATION MACRO ATTRIBUTES'
	],
	'00209116': [
		'PLANE ORIENTATION MACRO ATTRIBUTES'
	],
	'00209113': [
		'PLANE POSITION MACRO ATTRIBUTES'
	],
	'00700080': [
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00700081': [
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00700082': [
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00700083': [
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00700084': [
		'PRESENTATION STATE MODULE ATTRIBUTES'
	],
	'00081115': [
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES'
	],
	'00080054': [
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES'
	],
	'00880130': [
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES'
	],
	'00880140': [
		'PRESENTATION STATE MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES',
		'STUDY CONTENT MODULE ATTRIBUTES'
	],
	'00409096': [
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES'
	],
	'00409216': [
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES'
	],
	'00409211': [
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES'
	],
	'00409224': [
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES'
	],
	'00409225': [
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES'
	],
	'00409212': [
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES'
	],
	'00409210': [
		'REAL WORLD VALUE MAPPING MACRO ATTRIBUTES'
	],
	'00189170': [
		'RESPIRATORY SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00189171': [
		'RESPIRATORY SYNCHRONIZATION MODULE ATTRIBUTES'
	],
	'00080064': [
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181010': [
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181016': [
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181018': [
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181019': [
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181022': [
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181023': [
		'SC IMAGE EQUIPMENT MODULE ATTRIBUTES'
	],
	'00181012': [
		'SC IMAGE MODULE ATTRIBUTES'
	],
	'00181014': [
		'SC IMAGE MODULE ATTRIBUTES'
	],
	'2010015e': [
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00182010': [
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00182020': [
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00182030': [
		'SC MULTI-FRAME IMAGE MODULE ATTRIBUTES'
	],
	'00182001': [
		'SC MULTI-FRAME VECTOR MODULE ATTRIBUTES',
		'SCMULTI-FRAME VECTOR MODULE ATTRIBUTES'
	],
	'00182002': [
		'SC MULTI-FRAME VECTOR MODULE ATTRIBUTES',
		'SCMULTI-FRAME VECTOR MODULE ATTRIBUTES'
	],
	'00182003': [
		'SC MULTI-FRAME VECTOR MODULE ATTRIBUTES',
		'SCMULTI-FRAME VECTOR MODULE ATTRIBUTES'
	],
	'00182004': [
		'SC MULTI-FRAME VECTOR MODULE ATTRIBUTES',
		'SCMULTI-FRAME VECTOR MODULE ATTRIBUTES'
	],
	'00182005': [
		'SC MULTI-FRAME VECTOR MODULE ATTRIBUTES',
		'SCMULTI-FRAME VECTOR MODULE ATTRIBUTES'
	],
	'00182006': [
		'SC MULTI-FRAME VECTOR MODULE ATTRIBUTES',
		'SCMULTI-FRAME VECTOR MODULE ATTRIBUTES'
	],
	'0040071a': [
		'Slide Coordinates Module Attributes'
	],
	'0040072a': [
		'Slide Coordinates Module Attributes'
	],
	'0040073a': [
		'Slide Coordinates Module Attributes'
	],
	'0040074a': [
		'Slide Coordinates Module Attributes'
	],
	'004008d8': [
		'Slide Coordinates Module Attributes'
	],
	'004008da': [
		'Slide Coordinates Module Attributes'
	],
	'00283110': [
		'SOFTCOPY VOI LUT MODULE ATTRIBUTES'
	],
	'00080016': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080018': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080005': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080012': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080013': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080014': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080110': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080112': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'0008010c': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080114': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080115': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080103': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080116': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00080201': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'0018a002': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'0018a003': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'01000410': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'01000420': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'01000424': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'01000426': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'04000500': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'04000510': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'04000520': [
		'SOP COMMON MODULE ATTRIBUTES'
	],
	'00700042': [
		'SPATIAL TRANSFORMATION MODULE ATTRIBUTES'
	],
	'00700041': [
		'SPATIAL TRANSFORMATION MODULE ATTRIBUTES'
	],
	'0040050a': [
		'SPECIMEN IDENTIFICATION MODULE ATTRIBUTES'
	],
	'00400550': [
		'SPECIMEN IDENTIFICATION MODULE ATTRIBUTES'
	],
	'00400551': [
		'SPECIMEN IDENTIFICATION MODULE ATTRIBUTES'
	],
	'0040059a': [
		'SPECIMEN IDENTIFICATION MODULE ATTRIBUTES'
	],
	'004006fa': [
		'SPECIMEN IDENTIFICATION MODULE ATTRIBUTES'
	],
	'00200200': [
		'Synchronization Module Attributes'
	],
	'0018106a': [
		'Synchronization Module Attributes'
	],
	'0018106c': [
		'Synchronization Module Attributes'
	],
	'00181800': [
		'Synchronization Module Attributes'
	],
	'00181801': [
		'Synchronization Module Attributes'
	],
	'00181802': [
		'Synchronization Module Attributes'
	],
	'00180036': [
		'THERAPY MODULE ATTRIBUTES'
	],
	'00180038': [
		'THERAPY MODULE ATTRIBUTES'
	],
	'00180039': [
		'THERAPY MODULE ATTRIBUTES'
	],
	'00186018': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018601a': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018601c': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018601e': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186024': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186026': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018602c': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018602e': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186020': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186022': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186028': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018602a': [
		'US FRAME OF REFERENCE MODULE ATTRIBUTES',
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00082124': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'0008212a': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00280014': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082120': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'0040000a': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082122': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082127': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082128': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082129': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082130': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082132': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082240': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082242': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082244': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00082246': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00183100': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00183101': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00183102': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00183103': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00183104': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00183105': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185000': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185010': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00186031': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185012': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185022': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185024': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185026': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185027': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185028': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185029': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185050': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185210': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00185212': [
		'US IMAGE MODULE ATTRIBUTES'
	],
	'00186011': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186012': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186014': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186016': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186044': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186046': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186048': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018604a': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018604c': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018604e': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186050': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186052': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186054': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186056': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186058': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018605a': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186030': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186032': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186034': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186036': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186039': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018603b': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018603d': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0018603f': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186041': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'00186043': [
		'US REGION CALIBRATION MODULE ATTRIBUTES'
	],
	'0040b020': [
		'Waveform Annotation Module Attributes'
	],
	'0040a195': [
		'Waveform Annotation Module Attributes',
		'Waveform Annotation Module Attributes'
	],
	'0040a0b0': [
		'Waveform Annotation Module Attributes',
		'Waveform Module Attributes'
	],
	'0040a130': [
		'Waveform Annotation Module Attributes'
	],
	'0040a132': [
		'Waveform Annotation Module Attributes'
	],
	'0040a138': [
		'Waveform Annotation Module Attributes'
	],
	'0040a13a': [
		'Waveform Annotation Module Attributes'
	],
	'0040a180': [
		'Waveform Annotation Module Attributes'
	],
	'0008114a': [
		'Waveform Identification Module Attributes'
	],
	'00181068': [
		'Waveform Module Attributes'
	],
	'00181069': [
		'Waveform Module Attributes'
	],
	'0018106e': [
		'Waveform Module Attributes'
	],
	'003a0004': [
		'Waveform Module Attributes'
	],
	'003a0005': [
		'Waveform Module Attributes'
	],
	'003a0010': [
		'Waveform Module Attributes'
	],
	'003a001a': [
		'Waveform Module Attributes'
	],
	'003a0020': [
		'Waveform Module Attributes'
	],
	'003a0200': [
		'Waveform Module Attributes'
	],
	'003a0202': [
		'Waveform Module Attributes'
	],
	'003a0203': [
		'Waveform Module Attributes'
	],
	'003a0205': [
		'Waveform Module Attributes'
	],
	'003a0208': [
		'Waveform Module Attributes'
	],
	'003a0209': [
		'Waveform Module Attributes'
	],
	'003a020a': [
		'Waveform Module Attributes'
	],
	'003a020c': [
		'Waveform Module Attributes'
	],
	'003a0210': [
		'Waveform Module Attributes'
	],
	'003a0211': [
		'Waveform Module Attributes'
	],
	'003a0212': [
		'Waveform Module Attributes'
	],
	'003a0213': [
		'Waveform Module Attributes'
	],
	'003a0214': [
		'Waveform Module Attributes'
	],
	'003a0215': [
		'Waveform Module Attributes'
	],
	'003a0218': [
		'Waveform Module Attributes'
	],
	'003a021a': [
		'Waveform Module Attributes'
	],
	'003a0220': [
		'Waveform Module Attributes'
	],
	'003a0221': [
		'Waveform Module Attributes'
	],
	'003a0222': [
		'Waveform Module Attributes'
	],
	'003a0223': [
		'Waveform Module Attributes'
	],
	'5400100a': [
		'Waveform Module Attributes'
	],
	'00181114': [
		'XA POSITIONER MODULE ATTRIBUTES',
		'XRF POSITIONER MODULE ATTRIBUTES'
	],
	'00181500': [
		'XA POSITIONER MODULE ATTRIBUTES'
	],
	'00181520': [
		'XA POSITIONER MODULE ATTRIBUTES'
	],
	'00181521': [
		'XA POSITIONER MODULE ATTRIBUTES'
	],
	'00188151': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00188150': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'0018115e': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00400302': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00408302': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00400303': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00400306': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00400310': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00400312': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00400314': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00400316': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00400318': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES'
	],
	'00181191': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00187050': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY FILTRATION MODULE ATTRIBUTES'
	],
	'00187052': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY FILTRATION MODULE ATTRIBUTES'
	],
	'00187054': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY FILTRATION MODULE ATTRIBUTES'
	],
	'00181156': [
		'X-RAY ACQUISITION DOSE MODULE ATTRIBUTES',
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00181155': [
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181154': [
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'0018115a': [
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181161': [
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181162': [
		'X-RAY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181700': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00181702': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00181704': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00181706': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00181708': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00181710': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00181712': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00181720': [
		'X-RAY COLLIMATOR MODULE ATTRIBUTES'
	],
	'00187060': [
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00187062': [
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00187064': [
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00187065': [
		'X-RAY GENERATION MODULE ATTRIBUTES'
	],
	'00286040': [
		'X-RAY IMAGE MODULE ATTRIBUTES'
	],
	'00181134': [
		'X-RAY TABLE MODULE ATTRIBUTES'
	],
	'00181135': [
		'X-RAY TABLE MODULE ATTRIBUTES'
	],
	'00181137': [
		'X-RAY TABLE MODULE ATTRIBUTES'
	],
	'00181136': [
		'X-RAY TABLE MODULE ATTRIBUTES'
	],
	'00181460': [
		'X-RAY TOMOGRAPHY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181470': [
		'X-RAY TOMOGRAPHY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181480': [
		'X-RAY TOMOGRAPHY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181490': [
		'X-RAY TOMOGRAPHY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181491': [
		'X-RAY TOMOGRAPHY ACQUISITION MODULE ATTRIBUTES'
	],
	'00181495': [
		'X-RAY TOMOGRAPHY ACQUISITION MODULE ATTRIBUTES'
	]
};

/**
 * Function tries to get module names for tag. If module name cannot
 * be found, 'Undefined module group' is returned. Else array of module names is returned
 * @param tag tag to get module name for
 */
export function getModuleNamesForTag(tag: string): string[] {
    let translation = moduleNameTranslation[tag];
    if (translation === undefined) {
        return ['Undefined module group'];
    }
    return translation;
}
